version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_catalog
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql


  backend:
    build: ./backend
    container_name: backend-container
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    entrypoint: ["./wait-for-it.sh", "mysql:3306", "--", "node", "index.js"]

  frontend:
    build: ./frontend
    container_name: frontend-container
    depends_on:
      - backend
    ports:
      - "3001:3001"

volumes:
  mysql_data:
